version = 1

[[annotations]]
path = ".readthedocs.yaml"
SPDX-FileCopyrightText = [
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "docs/Makefile"
SPDX-FileCopyrightText = [
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "docs/make.bat"
SPDX-FileCopyrightText = [
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "pyproject.toml"
SPDX-FileCopyrightText = [
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "README.md"
SPDX-FileCopyrightText = [
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".github/**"
SPDX-FileCopyrightText = [
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "manim_extensions/algorithm/**"
SPDX-FileCopyrightText = [
    "2024 sinianluoye",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/sinianluoye/manim-algorithm"

[[annotations]]
path = "manim_extensions/automata/**"
SPDX-FileCopyrightText = [
    "2022 Sean Nelson",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/SeanNelsonIO/manim-automata"

[[annotations]]
path = "manim_extensions/circuit/**"
SPDX-FileCopyrightText = [
    "2025 Mr-FuzzyPenguin",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/Mr-FuzzyPenguin/manim-circuit"

[[annotations]]
path = "manim_extensions/compass/**"
SPDX-FileCopyrightText = [
    "2026 jj-math",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/jj-math/manim-compass"

[[annotations]]
path = "manim_extensions/data_structures/**"
SPDX-FileCopyrightText = [
    "2022 Hammad Nasir",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/drageelr/manim-data-structures"

[[annotations]]
path = "manim_extensions/gearbox/**"
SPDX-FileCopyrightText = [
    "2020 GarryBGoode",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/GarryBGoode/manim-GearBox"

[[annotations]]
path = "manim_extensions/meshes/**"
SPDX-FileCopyrightText = [
    "2022 bmmtstb",
    "99Vicky",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/bmmtstb/manim-meshes"

[[annotations]]
path = "manim_extensions/mindmap/**"
SPDX-FileCopyrightText = [
    "2026 jj-math",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/jj-math/manim-mindmap"

[[annotations]]
path = "manim_extensions/neural_network/**"
SPDX-FileCopyrightText = [
    "2024 Javier Pozo Miranda",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/JPM2002/manim-neural-network"

[[annotations]]
path = "manim_extensions/physics/**"
SPDX-FileCopyrightText = [
    "2024 Matheart",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/Matheart/manim-physics"

[[annotations]]
path = "manim_extensions/rubikscube/**"
SPDX-FileCopyrightText = [
    "2021 KingWampy",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/WampyCakes/manim-rubikscube"

[[annotations]]
path = "manim_extensions/sequence_diagram/**"
SPDX-FileCopyrightText = [
    "2023 Thomas Chen",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/foxnewsnetwork/manim-sequence-diagram"

[[annotations]]
path = "manim_extensions/tikz/**"
SPDX-FileCopyrightText = [
    "2023 Ralphie Raccoon",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/ralphieraccoon/manim-tikz"

[[annotations]]
path = "manim_extensions/mobjects.py"
SPDX-FileCopyrightText = [
    "2020 manim-kindergarten",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/manim-kindergarten/manim_sandbox"

[[annotations]]
path = "manim_extensions/animations.py"
SPDX-FileCopyrightText = [
    "2020 manim-kindergarten",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/manim-kindergarten/manim_sandbox"

[[annotations]]
path = "manim_extensions/__init__.py"
SPDX-FileCopyrightText = [
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "manim_extensions/geometry.py"
SPDX-FileCopyrightText = [
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "docs/source/_extensions/manim_directive.py"
SPDX-FileCopyrightText = [
    "2026 ExploreMaths",
    "2024 Manim Community"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "docs/source/_extensions/**"
SPDX-FileCopyrightText = [
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "docs/source/_static/custom.css"
SPDX-FileCopyrightText = [
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "docs/source/_static/responsiveSvg.js"
SPDX-FileCopyrightText = [
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "docs/source/conf.py"
SPDX-FileCopyrightText = [
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "docs/source/reference/algorithm/**/*.rst"
SPDX-FileCopyrightText = [
    "2024 sinianluoye",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/sinianluoye/manim-algorithm"

[[annotations]]
path = "docs/source/reference/automata/**/*.rst"
SPDX-FileCopyrightText = [
    "2022 Sean Nelson",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/SeanNelsonIO/manim-automata"

[[annotations]]
path = "docs/source/reference/circuit/**/*.rst"
SPDX-FileCopyrightText = [
    "2025 Mr-FuzzyPenguin",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/Mr-FuzzyPenguin/manim-circuit"

[[annotations]]
path = "docs/source/reference/compass/**/*.rst"
SPDX-FileCopyrightText = [
    "2026 jj-math",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/jj-math/manim-compass"

[[annotations]]
path = "docs/source/reference/data_structures/**/*.rst"
SPDX-FileCopyrightText = [
    "2022 Hammad Nasir",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/drageelr/manim-data-structures"

[[annotations]]
path = "docs/source/reference/gearbox/**/*.rst"
SPDX-FileCopyrightText = [
    "2020 GarryBGoode",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/GarryBGoode/manim-GearBox"

[[annotations]]
path = "docs/source/reference/meshes/**/*.rst"
SPDX-FileCopyrightText = [
    "2022 bmmtstb",
    "99Vicky",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/bmmtstb/manim-meshes"

[[annotations]]
path = "docs/source/reference/mindmap/**/*.rst"
SPDX-FileCopyrightText = [
    "2026 jj-math",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/jj-math/manim-mindmap"

[[annotations]]
path = "docs/source/reference/neural_network/**/*.rst"
SPDX-FileCopyrightText = [
    "2024 Javier Pozo Miranda",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/JPM2002/manim-neural-network"

[[annotations]]
path = "docs/source/reference/physics/**/*.rst"
SPDX-FileCopyrightText = [
    "2024 Matheart",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/Matheart/manim-physics"

[[annotations]]
path = "docs/source/reference/rubikscube/**/*.rst"
SPDX-FileCopyrightText = [
    "2021 KingWampy",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/WampyCakes/manim-rubikscube"

[[annotations]]
path = "docs/source/reference/sequence_diagram/**/*.rst"
SPDX-FileCopyrightText = [
    "2023 Thomas Chen",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/foxnewsnetwork/manim-sequence-diagram"

[[annotations]]
path = "docs/source/reference/tikz/**/*.rst"
SPDX-FileCopyrightText = [
    "2023 Ralphie Raccoon",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/ralphieraccoon/manim-tikz"

[[annotations]]
path = "docs/source/reference/basic/**/*.rst"
SPDX-FileCopyrightText = [
    "2020 manim-kindergarten",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/manim-kindergarten/manim_sandbox"

[[annotations]]
path = "docs/source/**/*.rst"
SPDX-FileCopyrightText = [
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "docs/source/_static/*.svg"
SPDX-FileCopyrightText = [
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "docs/source/_static/3Blue1Brown.mp4"
SPDX-FileCopyrightText = [
    "2015 3Blue1Brown"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "workflow/**"
SPDX-FileCopyrightText = [
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "tests/**"
SPDX-FileCopyrightText = [
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "manim_extensions/compass/compass/assets/**"
SPDX-FileCopyrightText = [
    "2026 jj-math",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "manim_extensions/meshes/data/models/armadillo.ply"
SPDX-FileCopyrightText = [
    "2022 bmmtstb",
    "99Vicky",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/bmmtstb/manim-meshes"

[[annotations]]
path = "manim_extensions/meshes/data/models/suzanne.ply"
SPDX-FileCopyrightText = [
    "2022 bmmtstb",
    "99Vicky",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/bmmtstb/manim-meshes"

[[annotations]]
path = "manim_extensions/meshes/data/models/tail_topper.stl"
SPDX-FileCopyrightText = [
    "2022 bmmtstb",
    "99Vicky",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/bmmtstb/manim-meshes"

[[annotations]]
path = "manim_extensions/meshes/shaders/**"
SPDX-FileCopyrightText = [
    "2022 bmmtstb",
    "99Vicky",
    "2026 ExploreMaths"
]
SPDX-License-Identifier = "MIT"
source = "https://github.com/bmmtstb/manim-meshes"