# SPDX-FileCopyrightText: 2026 ExploreMaths
# SPDX-License-Identifier: MIT
"""Abstract molecule base class for Manim chemistry.

This module provides the AbstractMolecule class as a template for all molecule implementations.

"""

from manim import DOWN, Tex, Text, VGroup
from typing import Any, Dict, Optional, Tuple, Union
from manim.mobject.opengl.opengl_mobject import OpenGLGroup
from abc import abstractmethod

import numpy as np

from ..utils import PubchemAPIManager
from ..manim_chemistry_molecule import MCMolecule


class AbstractMolecule:
    """
    Abstract molecule class used as a template to create
    all the other molecule classes.

    Parameters
    ----------
    args
        Positional arguments passed to subclass implementations.
    **kwargs
        Additional keyword arguments passed to subclass implementations.
    """

    group_class = VGroup

    def __init__(self, *args, **kwargs):
        """
        To be implemented on subclasses.
        """
        ...

    @classmethod
    def molecule_from_file(
        cls,
        filepath: Any,
        ignore_hydrogens: bool = True,
        ignore_all_hydrogens: bool = False,
        elements_data_dict: Optional[dict] = None,
        *args,
        **kwargs,
    ):
        """
        Reads a file and returns a single molecule from that file.

        By default retrieves the first molecule generated by the file.

        Parameters
        ----------
        filepath : str | Pathlike
            Path to the file
        ignore_hydrogens : bool, optional
            Whether to remove hydrogens bonded to carbon atoms.
            Defaults to ``True``.
        ignore_all_hydrogens : bool, optional
            Whether to remove every hydrogen atom. Defaults to ``False``.
        elements_data_dict : dict, optional
            Dictionary of custom element data. Defaults to ``None``.
        **kwargs
            Additional keyword arguments passed to the molecule constructor.

        Returns
        -------
        GraphMolecule
            GraphMolecule from the file.
        """
        mc_molecule = MCMolecule.construct_from_file(
            filepath=filepath,
            ignore_hydrogens=ignore_hydrogens,
            ignore_all_hydrogens=ignore_all_hydrogens,
            elements_data_dict=elements_data_dict,
        )
        if isinstance(mc_molecule, list):
            mc_molecule = mc_molecule[0]

        vertices, edges = cls.mc_molecule_to_atoms_and_bonds(mc_molecule=mc_molecule)
        return cls(vertices, edges, *args, **kwargs)

    @classmethod
    def multiple_molecules_from_file(
        cls,
        filepath: Any,
        ignore_hydrogens: bool = True,
        ignore_all_hydrogens: bool = False,
        elements_data_dict: Optional[dict] = None,
        *args,
        **kwargs,
    ) -> Union[OpenGLGroup, VGroup]:
        """
        Reads a file and returns a collection of molecules from that file as a OpenGLGroup or VGroup.

        Parameters
        ----------
        filepath : str | Pathlike
            Path to the molecule
        ignore_hydrogens : bool, optional
            Whether to remove hydrogens bonded to carbon atoms.
            Defaults to ``True``.
        ignore_all_hydrogens : bool, optional
            Whether to remove every hydrogen atom. Defaults to ``False``.
        elements_data_dict : dict, optional
            Dictionary of custom element data. Defaults to ``None``.
        **kwargs
            Additional keyword arguments passed to the molecule constructor.

        Returns
        -------
        OpenGLGroup
            OpenGLGroup with the molecules inside.

        Raises
        ------
        Exception
            In case the mc_molecules parsed is not a list.
        """
        mc_molecules = MCMolecule.construct_multiples_from_file(
            filepath=filepath,
            ignore_hydrogens=ignore_hydrogens,
            ignore_all_hydrogens=ignore_all_hydrogens,
            elements_data_dict=elements_data_dict,
        )

        if not isinstance(mc_molecules, list):
            raise Exception(f"Expected a list of molecules. Received {mc_molecules}")

        mmolecules = cls.group_class()
        for mc_molecule in mc_molecules:
            atoms, bonds = cls.mc_molecule_to_atoms_and_bonds(mc_molecule=mc_molecule)
            mmolecules.add(cls(atoms, bonds, *args, **kwargs))

        return mmolecules

    @classmethod
    def molecule_from_string(
        cls,
        string: str,
        format: str = "json",
        ignore_hydrogens: bool = True,
        ignore_all_hydrogens: bool = False,
        elements_data_dict: Optional[dict] = None,
        *args,
        **kwargs,
    ):
        """
        Reads a file and returns a single molecule from that file.

        By default retrieves the first molecule generated by the file.

        Parameters
        ----------
        string : str
            String with the molecule data.
        format : str, optional
            Format of the data. Defaults to ``"json"``.
        ignore_hydrogens : bool, optional
            Whether to remove hydrogens bonded to carbon atoms.
            Defaults to ``True``.
        ignore_all_hydrogens : bool, optional
            Whether to remove every hydrogen atom. Defaults to ``False``.
        elements_data_dict : dict, optional
            Dictionary of custom element data. Defaults to ``None``.
        **kwargs
            Additional keyword arguments passed to the molecule constructor.

        Returns
        -------
        ThreeDMolecule
            ThreeDMolecule from the string.
        """

        mc_molecule = MCMolecule.construct_from_string(
            string=string,
            format=format,
            ignore_hydrogens=ignore_hydrogens,
            ignore_all_hydrogens=ignore_all_hydrogens,
            elements_data_dict=elements_data_dict,
        )
        if isinstance(mc_molecule, list):
            mc_molecule = mc_molecule[0]

        vertices, edges = cls.mc_molecule_to_atoms_and_bonds(mc_molecule=mc_molecule)
        return cls(vertices, edges, *args, **kwargs)

    @classmethod
    def multiple_molecules_from_string(
        cls,
        string: str,
        format: str = "json",
        ignore_hydrogens: bool = True,
        ignore_all_hydrogens: bool = False,
        elements_data_dict: Optional[dict] = None,
        *args,
        **kwargs,
    ) -> OpenGLGroup:
        """
        Reads a file and returns a collection of molecules from that file as a OpenGLGroup.

        Parameters
        ----------
        string : str
            String with the molecule data.
        format : str, optional
            Format of the data. Defaults to ``"json"``.
        ignore_hydrogens : bool, optional
            Whether to remove hydrogens bonded to carbon atoms.
            Defaults to ``True``.
        ignore_all_hydrogens : bool, optional
            Whether to remove every hydrogen atom. Defaults to ``False``.
        elements_data_dict : dict, optional
            Dictionary of custom element data. Defaults to ``None``.
        **kwargs
            Additional keyword arguments passed to the molecule constructor.

        Returns
        -------
        OpenGLGroup
            OpenGLGroup with the molecules inside.

        Raises
        ------
        Exception
            In case the mc_molecules parsed is not a list.
        """

        mc_molecules = MCMolecule.construct_multiples_from_string(
            string=string,
            format=format,
            ignore_hydrogens=ignore_hydrogens,
            ignore_all_hydrogens=ignore_all_hydrogens,
            elements_data_dict=elements_data_dict,
        )

        if not isinstance(mc_molecules, list):
            raise Exception(f"Expected a list of molecules. Received {mc_molecules}")

        mmolecules = OpenGLGroup()
        for mc_molecule in mc_molecules:
            atoms, bonds = cls.mc_molecule_to_atoms_and_bonds(mc_molecule=mc_molecule)
            mmolecules.add(cls(atoms, bonds, *args, **kwargs))

        return mmolecules

    @classmethod
    def molecule_from_pubchem(
        cls,
        cid: Optional[str] = None,
        name: Optional[str] = None,
        smiles: Optional[str] = None,
        inchi: Optional[str] = None,
        three_d: bool = False,
        elements_data_dict: Optional[dict] = None,
        *args,
        **kwargs,
    ):
        """
        Generates a GraphMolecule from an identifier using PubChem API.

        Parameters
        ----------
        cid : Optional[str], optional
            Molecule cid. Defaults to None.
        name : Optional[str], optional
            Molecule name. Defaults to None.
        smiles : Optional[str], optional
            Molecule SMILES. Defaults to None.
        inchi : Optional[str], optional
            Molecule InChi. Defaults to None.
        three_d : bool, optional
            Whether to use three-dimensional data of the molecule.
            Defaults to ``False``.
        elements_data_dict : dict, optional
            Dictionary of custom element data. Defaults to ``None``.
        **kwargs
            Additional keyword arguments passed to the molecule constructor.

        Returns
        -------
        GraphMolecule
            GraphMolecule.
        """
        pubchem_api_manager = PubchemAPIManager(
            cid=cid, name=name, smiles=smiles, inchi=inchi, three_d=three_d
        )

        return cls.molecule_from_string(
            string=pubchem_api_manager.get_molecule(),
            format="json",
            elements_data_dict=elements_data_dict,
            *args,
            **kwargs,
        )

    @classmethod
    @abstractmethod
    def mc_molecule_to_atoms_and_bonds(
        cls, mc_molecule: MCMolecule
    ) -> Tuple[Dict, Dict]:
        """
        Transforms the structure of a mc_molecule to a (vertices, edges) tuple
        with the following structure:
        - Vertices: {<atom_index>: MCAtom}
        - Edges: {(<from_atom_index>, <to_atom_index>): MCBond}

        Parameters
        ----------
        mc_molecule : MCMolecule
            The MCMolecule object to transform.

        Returns
        -------
        Tuple[Dict, Dict]
            A tuple containing atoms and bonds dictionaries.
        """
        ...

    def add_molecule_name(
        self,
        name: Union[Text, Tex, str],
        direction: np.ndarray = DOWN,
        buff: float = 0.5,
        scale: float = 0.75,
        ):
        """Adds the name of the molecule.

        Parameters
        ----------
        name : Union[Text, Tex, str]
            Name of the molecule. Can either be a string, a Manim Tex or a Manim Text
        direction : numpy.ndarray, optional
            Position where to set the molecule name. Defaults to DOWN.
        buff : float, optional
            Distance between the name and the molecule. Defaults to 0.5.
        scale : float, optional
            Scale of the text. Defaults to 0.75.

        .. manim:: MMoleculeWithName

            from manim import *
            from manim_extensions.chemistry import MMoleculeObject

            class MMoleculeWithName(Scene):
                def construct(self):
                    molecule = MMoleculeObject.molecule_from_pubchem(name="acetone")
                    self.play(Write(molecule))
                    molecule.add_molecule_name(name="Acetone")
                    self.play(Write(molecule[-1]))
                    self.wait()

        .. manim:: GraphMoleculeWithName

            from manim import *
            from manim_extensions.chemistry import GraphMolecule

            class GraphMoleculeWithName(Scene):
                def construct(self):
                    molecule = GraphMolecule.molecule_from_pubchem(name="acetone")
                    self.play(Write(molecule))
                    molecule.add_molecule_name(name="Acetone")
                    self.play(Write(molecule.submobjects[-1]))
                    self.wait()

        """

        if isinstance(name, str):
            name = Text(name)

        name.scale(scale).next_to(self, direction=direction, buff=buff)
        self.add(name)
        return self