"""Electrostatic field helpers.

The classes in this module generate charge objects and electric-field vector
fields suitable for teaching and demonstration scenes in Manim.

Examples
--------
.. manim:: ElectrostaticsModuleDocExample
   :save_last_frame:

   from manim import *
   from manim_extensions.physics.electromagnetism import Charge, ElectricField

   class ElectrostaticsModuleDocExample(Scene):
       def construct(self):
           q1 = Charge(-1, LEFT + DOWN)
           q2 = Charge(2, RIGHT + DOWN)
           field = ElectricField(q1, q2)
           self.add(q1, q2, field)
"""

from __future__ import annotations
from typing import Iterable

from manim import normalize
from manim.constants import ORIGIN, TAU
from manim.mobject.geometry.arc import Arc, Dot
from manim.mobject.geometry.polygram import Rectangle
from manim.mobject.types.vectorized_mobject import VGroup
from manim.mobject.vector_field import ArrowVectorField
from manim.utils.color import BLUE, RED, RED_A, RED_D, color_gradient
import numpy as np


__all__ = [
    "Charge",
    "ElectricField",
]


class Charge(VGroup):
    """Visual representation of an electrostatic charge.

    Parameters
    ----------
    magnitude : float, optional
        Charge strength; positive values are red, negative values are blue.
    point : numpy.ndarray, optional
        Location of the charge in the scene.
    add_glow : bool, optional
        Whether to draw a soft glow around the charge.
    kwargs
        Additional arguments passed to :class:`~manim.mobject.types.vectorized_mobject.VGroup`.

    Examples
    --------
    .. manim:: ChargeExample
       :save_last_frame:

       from manim import *
       from manim_extensions.physics.electromagnetism.electrostatics import Charge

       class ChargeExample(Scene):
           def construct(self):
               pos = Charge(1, LEFT + DOWN)
               neg = Charge(-1, RIGHT + DOWN)
               self.add(pos, neg)
"""

    def __init__(
        self,
        magnitude: float = 1,
        point: np.ndarray = ORIGIN,
        add_glow: bool = True,
        **kwargs,
    ) -> None:
        """Initialize Charge."""
        VGroup.__init__(self, **kwargs)
        self.magnitude = magnitude
        self.point = point
        self.radius = (abs(magnitude) * 0.4 if abs(magnitude) < 2 else 0.8) * 0.3

        if magnitude > 0:
            label = VGroup(
                Rectangle(width=0.32 * 1.1, height=0.006 * 1.1).set_z_index(1),
                Rectangle(width=0.006 * 1.1, height=0.32 * 1.1).set_z_index(1),
            )
            color = RED
            layer_colors = [RED_D, RED_A]
            layer_radius = 4
        else:
            label = Rectangle(width=0.27, height=0.003)
            color = BLUE
            layer_colors = ["#3399FF", "#66B2FF"]
            layer_radius = 2

        if add_glow:  # use many arcs to simulate glowing
            layer_num = 80
            color_list = color_gradient(layer_colors, layer_num)
            opacity_func = lambda t: 1500 * (1 - abs(t - 0.009) ** 0.0001)
            rate_func = lambda t: t**2

            for i in range(layer_num):
                self.add(
                    Arc(
                        radius=layer_radius * rate_func((0.5 + i) / layer_num),
                        angle=TAU,
                        color=color_list[i],
                        stroke_width=101
                        * (rate_func((i + 1) / layer_num) - rate_func(i / layer_num))
                        * layer_radius,
                        stroke_opacity=opacity_func(rate_func(i / layer_num)),
                    ).shift(point)
                )

        self.add(Dot(point=self.point, radius=self.radius, color=color))
        self.add(label.scale(self.radius / 0.3).shift(point))
        for mob in self:
            mob.set_z_index(1)


class ElectricField(ArrowVectorField):
    """Vector field generated by one or more electrostatic charges.

    Parameters
    ----------
        charges
            The charges affecting the electric field.
        kwargs
            Additional parameters to be passed to ``ArrowVectorField``.

    Examples
    --------
    .. manim:: ElectricFieldExample
       :save_last_frame:

       from manim import *
       from manim_extensions.physics.electromagnetism.electrostatics import (
           Charge, ElectricField,
       )

       class ElectricFieldExample(Scene):
           def construct(self):
               q1 = Charge(1, LEFT + DOWN)
               q2 = Charge(-1, RIGHT + DOWN)
               field = ElectricField(q1, q2)
               self.add(q1, q2, field)
"""

    def __init__(self, *charges: Charge, **kwargs) -> None:
        """Initialize ElectricField."""
        self.charges = charges
        positions = []
        magnitudes = []
        for charge in charges:
            positions.append(charge.get_center())
            magnitudes.append(charge.magnitude)
        super().__init__(lambda p: self._field_func(p, positions, magnitudes), **kwargs)

    def _field_func(
        self,
        p: np.ndarray,
        positions: Iterable[np.ndarray],
        magnitudes: Iterable[float],
    ) -> np.ndarray:
        """Compute the electric field vector at a point using Coulomb's law.

        Parameters
        ----------
        p : numpy.ndarray
            Field point at which the electric field is evaluated.
        positions : iterable of numpy.ndarray
            Positions of the source charges.
        magnitudes : iterable of float
            Charge magnitudes (in arbitrary units) for each source charge.

        Returns
        -------
        numpy.ndarray
            The net electric field vector at point *p*.
        """
        field_vect = np.zeros(3)
        for p0, mag in zip(positions, magnitudes):
            r = p - p0
            dist = np.linalg.norm(r)
            if dist < 0.1:
                return np.zeros(3)
            field_vect += mag / dist**2 * normalize(r)
        return field_vect